export enum TemplateTypeEnum {
	TEMPLATE_TYPE_CODE_PARSER = 'TEMPLATE_TYPE_CODE_PARSER',
	TEMPLATE_TYPE_INTERFACE_PARSE = 'TEMPLATE_TYPE_INTERFACE_PARSE',
	TEMPLATE_TYPE_INTERFACE_PARSE_OUTPUT = 'TEMPLATE_TYPE_INTERFACE_OUTPUT',
	TEMPLATE_TYPE_INTERFACE_PARSER = 'TEMPLATE_TYPE_INTERFACE_PARSER',
}
